name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/apt-get-install-action@v2

    - name: install virtualbox
      uses: actions/apt-get-install-action@v2
      with:
        pkg: virtualbox

    - name: Show Vagrant version
      run: vagrant --version

    - name: Run vagrant up
      run: pushd vagrant/ ; VAGRANT_VAGRANTFILE=Vagrantfile.debian12_64 vagrant up; popd

    - name: ssh into box after boot
      run: vagrant ssh -c "echo 'hello world'"
