
name: vagrant-all

on: [push]

jobs:
  vagrant-all:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./vagrant

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
        
    - name: install vagrant/qemu provider
      uses: ConorMacBride/install-package@v1.1.0
      with:
        apt: vagrant qemu-kvm virtualbox libvirt-daemon libvirt-daemon-driver-vbox

    - name: test Vagrantfile.debian11_64
      if: always()
      run: sudo VAGRANT_VAGRANTFILE=Vagrantfile.debian11_64 vagrant up --provision --provider=virtualbox

    - name: test Vagrantfile.debian12_64
      if: always()
      run: sudo VAGRANT_VAGRANTFILE=Vagrantfile.debian12_64 vagrant up --provision --provider=virtualbox

    - name: test Vagrantfile.mint20_64
      if: always()
      run: sudo VAGRANT_VAGRANTFILE=Vagrantfile.debian12_64 vagrant up --provision --provider=virtualbox

    - name: test Vagrantfile.mint21_64
      if: always()
      run: sudo VAGRANT_VAGRANTFILE=Vagrantfile.debian12_64 vagrant up --provision --provider=virtualbox

    - name: test Vagrantfile.mint22_64
      if: always()
      run: sudo VAGRANT_VAGRANTFILE=Vagrantfile.debian12_64 vagrant up --provision --provider=virtualbox
