name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: ubuntu-latest
    #defaults:
    #  run:
    #    working-directory: ./vagrant

    
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
        
    - name: install basic dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1.4.2
      #uses: ConorMacBride/install-package@v1.1.0
      with:
        apt: ansible, git

    - name: run playbook
      run: sudo ansible-playbook --connection=local -i localhost, tidal.play.yml
