name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vagrant

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
        
    - name: install virtualbox
      uses: awalsh128/cache-apt-pkgs-action@v1.4.2
      with:
        packages: vagrant, virtualbox

    - name: Show Vagrant version
      run: "echo $PWD; ls -la"

    - name: Run vagrant up
      run: VAGRANT_VAGRANTFILE=Vagrantfile.debian12_64 vagrant up --provider virtualbox

    - name: ssh into box after boot
      run: vagrant ssh -c "echo 'hello world'"
