
name: vagrant-all

on: [push]

jobs:
  debian11:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vagrant

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
        
    - name: install virtualbox
      #uses: awalsh128/cache-apt-pkgs-action@v1.4.2
      uses: ConorMacBride/install-package@v1.1.0
      with:
        apt: vagrant qemu-kvm libvirt-clients libvirt-daemon-system bridge-utils libvirt-daemon

    - name: Show Vagrant version
      run: "echo $PWD; ls -la"

    - name: Run vagrant up
      run: VAGRANT_VAGRANTFILE=Vagrantfile.debian11_64 vagrant up --provision --provider=libvirt

    - name: ssh into box after boot
      run: vagrant ssh -c "echo 'hello world'"
